# ############################################################################
# Model: Symmetric BERT + CE loss
# Authors: Luca Della Libera 2023
# ############################################################################

experiment_name: SymmetricBERTVAE

seed: 0
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data preparation
data_folder: !PLACEHOLDER
train_splits: ["train-clean-100", "train-clean-360", "train-other-500"]
dev_splits: ["dev-clean"]
test_splits: ["test-clean"]
skip_prep: False
train_csv: !ref <output_folder>/train.csv
valid_csv: !ref <output_folder>/dev-clean.csv
test_csv: !ref <output_folder>/test-clean.csv

# Output directories
output_folder: !ref results/<experiment_name>/<seed>
save_folder: !ref <output_folder>/save

# Training parameters
train_batch_size: 32
valid_batch_size: 32
train_num_workers: 6
valid_num_workers: 6

sorting: ascending
avoid_if_longer_than: 10  # Remove utterances longer than 10s (open microphones)

model_variant: bert-base-uncased
freeze_encoder: True

num_epochs: 20
lr: 0.001
improvement_threshold: 0.0025
annealing_factor: 0.8
patient: 3
nonfinite_patience: 10
max_grad_norm: 5.0
auto_mix_prec: True
gradient_checkpointing: False
ckpt_interval_minutes: 600

# Dataloader options
train_dataloader_kwargs:
    batch_size: !ref <train_batch_size>
    num_workers: !ref <train_num_workers>

valid_dataloader_kwargs:
    batch_size: !ref <valid_batch_size>
    num_workers: !ref <valid_num_workers>

# Modules
vae: !new:models.bert_vae.SymmetricBERTVAE
    source: !ref <model_variant>
    save_path: !ref <save_folder>/huggingface
    freeze_encoder: !ref <freeze_encoder>

loss: !new:torch.nn.CrossEntropyLoss
    ignore_index: 0  # Default pad token ID
kl_weight: 0.000001

modules:
    vae: !ref <vae>

# Optimizers
opt_class: !name:torch.optim.AdamW
    lr: !ref <lr>

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: !ref <improvement_threshold>
    annealing_factor: !ref <annealing_factor>
    patient: !ref <patient>

# Performance metrics
wer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    split_tokens: True

# Counters, checkpointers, loggers, etc.
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <num_epochs>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <vae>
        scheduler: !ref <lr_annealing>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <output_folder>/<experiment_name>.txt
