# ############################################################################
# Model: Whisper Encoder + DNN + CTC
# Augmentation: SpecAugment
# Authors: Luca Della Libera 2022
# ############################################################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data preparation
dataset_size: medium
dataset_version: "10_0"
dataset_dir: !ref ../data/common_voice_<dataset_version>
manifest_dir: !ref <dataset_dir>_<dataset_size>
locales: null # All languages

# Data files and directories
output_dir: !ref results/multilingual/<dataset_size>/whisper_large_encoder_frozen/<seed>
wer_file: !ref <output_dir>/wer.txt
save_dir: !ref <output_dir>/save
train_log: !ref <output_dir>/train_log.txt

# We remove utterances longer than 10s in the train/dev/test sets as
# longer sentences certainly correspond to "open microphones".
avoid_if_longer_than: 10.0

ckpt_interval_minutes: 15 # save checkpoint every N min

# Training parameters
number_of_epochs: 10
lr_model: 1.0
lr_whisper: 0.0001
sorting: ascending
auto_mix_prec: True

# With data_parallel batch_size is split into N jobs
# With DDP batch_size is multiplied by N jobs
# Must be 8 per GPU to fit 32GB of VRAM
batch_size: 8
test_batch_size: 8

# BPE parameters
token_type: char  # ["unigram", "bpe", "char"]
character_coverage: 1.0

# Feature parameters
sample_rate: 16000

# Dataloader options
train_dataloader_opts:
    batch_size: !ref <batch_size>
    shuffle: True
    num_workers: 6

valid_dataloader_opts:
    batch_size: !ref <test_batch_size>
    num_workers: 6

test_dataloader_opts:
    batch_size: !ref <test_batch_size>
    num_workers: 6

# Model parameters
whisper_hub: openai/whisper-large
whisper_output_dim: 1280
freeze_whisper: True
activation: !name:torch.nn.LeakyReLU
dropout: 0.15
dnn_neurons: 1024
output_neurons: 1218

# Decoding parameters
blank_index: 0  # index(blank/unk) = 0
#label_smoothing: 0.0 TODO: check

# Time domain SpecAugment
augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

# Models
whisper: !new:speechbrain.lobes.models.huggingface_whisper.HuggingFaceWhisper
   source: !ref <whisper_hub>
   freeze: !ref <freeze_whisper>
   save_path: !ref <save_dir>/whisper_checkpoint
   encoder_only: True

enc: !new:speechbrain.nnet.containers.Sequential
    input_shape: [null, null, !ref <whisper_output_dim>]
    linear1: !name:speechbrain.nnet.linear.Linear
        n_neurons: !ref <dnn_neurons>
        bias: True
    bn1: !name:speechbrain.nnet.normalization.BatchNorm1d
    activation: !new:torch.nn.LeakyReLU
    drop: !new:torch.nn.Dropout
        p: !ref <dropout>
    linear2: !name:speechbrain.nnet.linear.Linear
        n_neurons: !ref <dnn_neurons>
        bias: True
    bn2: !name:speechbrain.nnet.normalization.BatchNorm1d
    activation2: !new:torch.nn.LeakyReLU
    drop2: !new:torch.nn.Dropout
        p: !ref <dropout>
    linear3: !name:speechbrain.nnet.linear.Linear
        n_neurons: !ref <dnn_neurons>
        bias: True
    bn3: !name:speechbrain.nnet.normalization.BatchNorm1d
    activation3: !new:torch.nn.LeakyReLU

ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dnn_neurons>
    n_neurons: !ref <output_neurons>

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

ctc_cost: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>

modules:
    whisper: !ref <whisper>
    enc: !ref <enc>
    ctc_lin: !ref <ctc_lin>

model: !new:torch.nn.ModuleList
    - [!ref <enc>, !ref <ctc_lin>]

# Optimizers
opt_class: !name:torch.optim.Adadelta
    lr: !ref <lr_model>
    rho: 0.95
    eps: 1.e-8

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr_model>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

opt_class_whisper: !name:torch.optim.Adam
    lr: !ref <lr_whisper>

lr_annealing_whisper: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr_whisper>
    improvement_threshold: 0.0025
    annealing_factor: 0.9
    patient: 0

# Metrics
error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    split_tokens: True

# Misc
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_dir>
    recoverables:
        whisper: !ref <whisper>
        model: !ref <model>
        scheduler: !ref <lr_annealing>
        scheduler_whisper: !ref <lr_annealing_whisper>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>
