# ################################
# Model: Whisper (Encoder only) + DNN + CTC
# Augmentation: TimeDomainSpecAugment
# Authors: Pooneh Mousavi 2022
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1986
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_dir: !ref results/ar/train_whisper_char/<seed>
wer_file: !ref <output_dir>/wer.txt
save_dir: !ref <output_dir>/save
train_log: !ref <output_dir>/train_log.txt

# URL for the biggest Fairseq english whisper model.
whisper_hub: openai/whisper-base

# Data files
dataset_size: small
dataset_version: "10_0"
dataset_dir: !ref data/common_voice_<dataset_version>
manifest_dir: !ref <dataset_dir>_<dataset_size>
locales: ["ar"] # English


# Training parameters
number_of_epochs: 2
lr: 1.0
lr_whisper: 0.00005
sorting: ascending
auto_mix_prec: False
sample_rate: 16000

# BPE parameters
token_type: char  # ["unigram", "bpe", "char"]
character_coverage: 1.0


# With data_parallel batch_size is split into N jobs
# With DDP batch_size is multiplied by N jobs
batch_size: 6
test_batch_size: 8

# Dataloader options
train_dataloader_opts:
   batch_size: !ref <batch_size>

valid_dataloader_opts:
   batch_size: !ref <batch_size>

test_dataloader_opts:
   batch_size: !ref <test_batch_size>

# Model parameters
activation: !name:torch.nn.LeakyReLU
dnn_layers: 2
dnn_neurons: 1024
freeze_whisper: False
whisper_output_dim: 512


# Outputs
output_neurons: 38  # BPE size, index(blank/eos/bos) = 0

# Decoding parameters
blank_index: 0

#
# Functions and classes
#
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
   limit: !ref <number_of_epochs>

augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
   sample_rate: !ref <sample_rate>
   speeds: [95, 100, 105]

enc: !new:speechbrain.nnet.containers.Sequential
   input_shape: [null, null, !ref <whisper_output_dim>]
   linear1: !name:speechbrain.nnet.linear.Linear
      n_neurons: !ref <dnn_neurons>
      bias: True
   bn1: !name:speechbrain.nnet.normalization.BatchNorm1d
   activation: !new:torch.nn.LeakyReLU
   drop: !new:torch.nn.Dropout
      p: 0.15
   linear2: !name:speechbrain.nnet.linear.Linear
      n_neurons: !ref <dnn_neurons>
      bias: True
   bn2: !name:speechbrain.nnet.normalization.BatchNorm1d
   activation2: !new:torch.nn.LeakyReLU
   drop2: !new:torch.nn.Dropout
      p: 0.15
   linear3: !name:speechbrain.nnet.linear.Linear
      n_neurons: !ref <dnn_neurons>
      bias: True
   bn3: !name:speechbrain.nnet.normalization.BatchNorm1d
   activation3: !new:torch.nn.LeakyReLU

whisper: !new:speechbrain.lobes.models.huggingface_whisper.HuggingFaceWhisper
   source: !ref <whisper_hub>
   freeze: !ref <freeze_whisper>
   save_path: !ref <save_dir>/whisper_checkpoint
   encoder_only: True


ctc_lin: !new:speechbrain.nnet.linear.Linear
   input_size: !ref <dnn_neurons>
   n_neurons: !ref <output_neurons>

log_softmax: !new:speechbrain.nnet.activations.Softmax
   apply_log: True

ctc_cost: !name:speechbrain.nnet.losses.ctc_loss
   blank_index: !ref <blank_index>

modules:
   whisper: !ref <whisper>
   enc: !ref <enc>
   ctc_lin: !ref <ctc_lin>

model: !new:torch.nn.ModuleList
   - [!ref <enc>, !ref <ctc_lin>]

model_opt_class: !name:torch.optim.Adadelta
   lr: !ref <lr>
   rho: 0.95
   eps: 1.e-8

whisper_opt_class: !name:torch.optim.Adam
   lr: !ref <lr_whisper>

lr_annealing_model: !new:speechbrain.nnet.schedulers.NewBobScheduler
   initial_value: !ref <lr>
   improvement_threshold: 0.0025
   annealing_factor: 0.8
   patient: 0

lr_annealing_whisper: !new:speechbrain.nnet.schedulers.NewBobScheduler
   initial_value: !ref <lr_whisper>
   improvement_threshold: 0.0025
   annealing_factor: 0.9
   patient: 0

label_encoder: !new:speechbrain.dataio.encoder.CTCTextEncoder

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
   checkpoints_dir: !ref <save_dir>
   recoverables:
      whisper: !ref <whisper>
      model: !ref <model>
      scheduler_model: !ref <lr_annealing_model>
      scheduler_whisper: !ref <lr_annealing_whisper>
      counter: !ref <epoch_counter>
      tokenizer: !ref <label_encoder>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
   save_file: !ref <train_log>

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
   split_tokens: True